from math import pi

COLOR_MODE_RGBA = 'RGBA'

ACTION_DESELECT = 'DESELECT'
ACTION_SELECT = 'SELECT'

DEFAULT_RENDER_ENGINE = 'CYCLES'

IMAGE_EXTENSION = '.png'

LIGHT_TYPE_SUN = 'SUN'
LIGHT_TYPE_POINT = 'POINT'
LIGHT_TYPE_LIGHT = 'LIGHT'

DEFAULT_RESOLUTION_X = 800
DEFAULT_RESOLUTION_Y = 800
DEFAULT_RESOLUTION_PERCENTAGE = 100
DEFAULT_RENDER_FOLDER = 'rocks'
DEFAULT_RENDER_NAME = 'render'

TAU = 2 * pi
